# Main Page Setup
title: SuHo Yu's Portfolio

# Hero Section
name: SuHo Yu
headline: >-
  Where Systems Engineering Meets the Sky – Bridging autonomous aerial systems, robotics, and electric propulsion through hands-on design and flight-tested research.
description: >-
  Aerospace & robotics systems engineer specializing in electric propulsion, UAV/UAM integration, and flight control architecture.
  Experienced in full-stack platform development—from CAD modeling and structural fabrication to high-voltage battery integration and autonomous flight testing.
  Bridging hardware and autonomy with proven results in government-funded eVTOL and aerial mobility projects.

profile_image: ./assets/images/profile-image/me.jpeg

resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing

external-links:
  linkedin: suho-yu
  github: yoosuho
  youtube: jenk5109

skills:
  - category: 3D Modeling
    tools:
      - Fusion 360 (Autodesk)
      - Solidworks
      - CATIA (Dassault Systèmes)
      - Onshape
      - Blender (for visualization or animation)

  - category: Prototyping / Manufacturing
    tools:
      - CNC Milling (setup, toolpath generation, and operation)
      - CAM Programming (Fusion CAM, Mastercam)
      - Manual Machining (lathe, drill press, cutting, grinding)
      - TIG Welding
      - FDM 3D Printing
      - Laser Cutting
      - Metal 3D Printing (DMLS or similar)
      - Custom Battery Pack Fabrication
      - Hand-built Frame Assembly (no jig, full alignment by hand)
      - Full-stack Mechanical Fabrication (from raw metal to functional assembly)
      - Arduino / Raspberry Pi

  - category: Battery & Power Systems
    tools:
      - Custom BMS Development (STM32-based)
      - CAN / UAVCAN Communication Integration
      - High Voltage Battery Architecture (12S–14S)
      - Energy System Compliance (per AC 21.17-4)
      - Thermal Management (air-cooled + passive strategies)

  - category: Embedded Systems / Control
    tools:
      - Pixhawk / Cube Flight Controllers
      - Mission Planner / QGroundControl
      - ESC Tuning (BLHeli, Hobbywing, etc.)
      - RTOS (basic integration)
      - PID Tuning / Sensor Fusion (IMU, GPS)
      - Serial & CAN Bus Debugging

  - category: PCB Design / Electronics
    tools:
      - KiCad
      - Eagle
      - Basic STM32 Firmware Development
      - Breadboarding for Circuit Prototyping

  - category: System Design / Architecture
    tools:
      - Model-Based Design (Simulink-level)
      - Fault-Tolerant Control (motor failure resilience)
      - System Integration (propulsion, frame, BMS, ESC, avionics)
      - DO-178C Compliance Workflow (LDRA-based static/dynamic validation)
      - Vibration Analysis (real-world battery module & drone)

  - category: Standards / Safety / Certification
    tools:
      - Root Cause Analysis (5 Whys, Fishbone Diagram)
      - FMEA (DFMEA, PFMEA)
      - AC 21.17-4 Certification Planning (Energy System CCL)
      - Safety Tether Test Protocols

  - category: Soft Skills / Communication
    tools:
      - Technical Presentation (FTC, Government R&D meetings)
      - Cross-functional Team Leadership
      - Engineering Documentation (specs, test reports, checklists)
      - Public-facing Technical Storytelling (YouTube Engineering Vlog)

formspree-key: https://formspree.io/f/{8-digit-key}

colors:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects
